### PR TITLE
Fix for Alpha Sapphire

### PR DESCRIPTION
**Pull request by WhatAboutGaming**
Fixed to work with Pokemon Randomized Alpha Sapphire, Send on Clicking fixed, now works on Theater Mode

### CODE REVIEW

**Comment by MattiasBuelens** [comment]
This fix should also be copied over to the `gh-pages` to make users find the updated version.

But before you push out a new release: Greasemonkey support is still broken, see #10.

**Comment by lostcoaster** [comment]
@MattiasBuelens Actually this script is being served from [https://raw.githubusercontent.com/lostcoaster/twitch-touches-pokemon/master/touch.user.js](https://raw.githubusercontent.com/lostcoaster/twitch-touches-pokemon/master/touch.user.js) (to fix the mimetype as I recall), so master branch update is enough.

But anyway, I fast-forwarded the other branch in case it would be used. Thanks for the suggestion.

**Comment by MattiasBuelens** [comment]
@lostcoaster It seems like some people (like @WhatAboutGaming) are using [the code snippet from your original reddit post](http://redd.it/247cvf) for their bookmarklet, which *does* refer to the version on GitHub Pages:
```js
javascript:(function(){document.body.appendChild(document.createElement('script')).src='http://lostcoaster.github.io/twitch-touches-pokemon/touch.user.js';})();
```

**Comment by WhatAboutGaming** [comment]
@MattiasBuelens Yes, I had to make a snippet in the mean time while I was waiting for @lostcoaster to deploy the changes.

**Pull request merged**
